更新名词选择
shengxinjing/programmer-job-blacklist pull request #339
Opened 2020-07-03 02:03 UTC by fulldecent

2020-07-04 00:34 UTC, vczh commented
甚至搜不到这个词

2020-07-04 00:35 UTC, vczh requested changes
甚至搜不到这个词

2020-09-28 06:50 UTC, fliaj commented
这啥

2020-09-28 19:57 UTC, fulldecent commented
现代人都不说”黑名单“这个词。我就这么建议另一个词。

中文不是我的母语，如果别的词会更好请推荐。

---

Off topic： 好几年全我也是个白帽子想帮世纪佳缘个忙。我也一样发现他们不欢迎白帽子。https://privacylog.blogspot.com/2012/09/restricting-user-content-case-study.html

2020-09-29 02:13 UTC, godfather1103 commented
估计是想用“禁止名单”吧，但是机器翻译成了“止名单”

2020-09-29 04:29 UTC, TuingLi commented
这就有点搞笑了，黑人问题是美洲那边的问题，和我们中国有个屁的关系？提供的列表是中国程序员找工作的黑名单，改个禁止名单有意思？这么搞的话，以后是不是都不能出现“黑”这个字了？“黑色”这玩意要不您也想个办法改一下啊，要不然黑人看着多难受啊？
On Sep 29, 2020, 10:14 +0800, Jack Chu , wrote:
> 估计是想用“禁止名单”吧，但是机器翻译成了“止名单”
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-09-29 07:34 UTC, godfather1103 commented
> 这就有点搞笑了，黑人问题是美洲那边的问题，和我们中国有个屁的关系？提供的列表是中国程序员找工作的黑名单，改个禁止名单有意思？这么搞的话，以后是不是都不能出现“黑”这个字了？“黑色”这玩意要不您也想个办法改一下啊，要不然黑人看着多难受啊？
> […](#)
> On Sep 29, 2020, 10:14 +0800, Jack Chu , wrote: 估计是想用“禁止名单”吧，但是机器翻译成了“止名单” — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

形式主义

2020-09-29 07:39 UTC, gangzhigm commented
不建议通过

2020-09-29 08:39 UTC, lxyfish111 commented
不建议通过

2020-09-29 21:41 UTC, fulldecent commented
> 黑人问题是美洲那边的问题。

谁把”黑名“说出“不好名”的意思就是问题。别的“黑”子随便您用。

2020-09-30 03:50 UTC, ebgaaron commented
black is not a bad word, blacklist is not a bad word too. we always use a
word and its antonym, but this doesn't mean we think the word or its
antonym is bad.  I like wear black clothes, we Chinese all born black hair,
black eyes, we are proud of that. we use blacklist only as a normal noun, I
believe all Chinese programmers who use this word don't think anything bad
that you thought, we use the word just because conventions. You are too
sensitive to the use of this word.


William Entriken <notifications@github.com> 于2020年9月30日周三 上午5:42写道：

> 黑人问题是美洲那边的问题。
>
> 谁把”黑名“说出“不好名”的意思就是问题。别的“黑”子随便您用。
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/shengxinjing/programmer-job-blacklist/pull/339#issuecomment-701006307>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFON6WNHPVSY5DWHP7FUBGTSIJIC7ANCNFSM4OPMRUOA>
> .
>

2025-06-05 05:16 UTC, closed without merging